name: 'Security Scan - Docker & Terraform'
description: 'Automated security scanning for Dockerfiles and Terraform using Hadolint, Trivy, and Terrascan with auto issue creation'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  docker-context:
    default: '.'
    required: false
    description: 'Diretório onde está o Dockerfile dentro do repo'

runs:
  using: composite
  steps:

    - name: Install Dependencies
      shell: bash
      run: | 
        set -euo pipefail
        sudo apt-get update -y && sudo apt-get install curl jq wget apt-transport-https gnupg lsb-release -y

    - name: Install Apps for Scan
      shell: bash
      run: | 
        # Install Hadolint
        curl -L https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint \
        && chmod +x /usr/local/bin/hadolint

        # Install Trivy
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

        # Terrascan
        TERRASCAN_URL=$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest \
          | jq -r '.assets[] | select(.name | test("_Linux_x86_64.tar.gz$")) | .browser_download_url')

        curl -sL "$TERRASCAN_URL" -o terrascan.tar.gz
        tar -xf terrascan.tar.gz terrascan && sudo install terrascan /usr/local/bin && rm terrascan terrascan.tar.gz
        terrascan

    - name: Checkout
      uses: actions/checkout@v4

    - name: Scan Docker
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        BUILD_CONTEXT:  ${{ github.event.inputs.docker-context }}
      run: |
        bash "${{ github.action_path }}/scripts/scan-docker.sh"

    - name: Scan Terraform
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        bash "${{ github.action_path }}/scripts/scan-terraform.sh"

    - name: Fail If Problems Were Found
      shell: bash
      run: |
        if [ -f "$GITHUB_WORKSPACE/issues_found.flag" ]; then
          echo "Vulnerabilidades encontradas — falhando job"
          exit 1
        else
          echo "Nenhum problema pendente"
        fi